name       : bibata-cursors
version    : 2.0.3
release    : 1
source     :
    - https://github.com/ful1e5/Bibata_Cursor/releases/download/v2.0.3/Bibata.tar.gz : 1664a1e848707e643362eb772a38f077a4cac6362ca39f5705f59e85128b270c
homepage   : https://github.com/KaizIqbal/Bibata_Cursor
license    : GPL-3.0-or-later
component  : desktop.theme
summary    : Material Based Cursor
description: |
    Bibata is OpenSource, Compact and Material Designed Cursor set. This project masterelop for improve Cursor Experience. This cursor theme pack include four variants: Bibata-Amber, Bibata Classic, Bibata Ice and Bibata Oil.
install    : |
    install -dm00644 $installdir/usr/share/icons
    cp -r Bibata-Modern-Amber     $installdir/usr/share/icons/Bibata-Modern-Amber
    cp -r Bibata-Modern-Classic $installdir/usr/share/icons/Bibata-Modern-Classic
    cp -r Bibata-Modern-Ice $installdir/usr/share/icons/Bibata-Modern-Ice
    cp -r Bibata-Original-Amber     $installdir/usr/share/icons/Bibata-Original-Amber
    cp -r Bibata-Original-Classic $installdir/usr/share/icons/Bibata-Original-Classic
    cp -r Bibata-Original-Ice $installdir/usr/share/icons/Bibata-Original-Ice
